# Generated by Django 4.2.2 on 2023-08-03 17:25

import customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Adminregister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Order_list",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("mobile_no", models.IntegerField()),
                ("email", models.CharField(max_length=15)),
                (
                    "prod_img",
                    models.ImageField(
                        blank=True, null=True, upload_to=customer.models.filepath
                    ),
                ),
                ("prod_name", models.CharField(max_length=255)),
                ("price", models.IntegerField()),
                ("aadhar", models.IntegerField()),
                ("driving_license", models.CharField(max_length=255)),
                ("pan_card", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prod_img",
                    models.ImageField(
                        blank=True, null=True, upload_to=customer.models.filepath
                    ),
                ),
                ("prod_name", models.CharField(max_length=255)),
                ("price", models.IntegerField()),
                ("mileage", models.CharField(max_length=255)),
                ("color", models.CharField(max_length=255)),
                ("cc", models.CharField(max_length=255)),
            ],
        ),
    ]
